title: alexander lerch
author: alexander lerch
email: info@audiocontentanalysis.org
description: > # this means to ignore newlines until "show_exerpts:"
  personal blog
show_excerpts: true # set to true to show excerpts on the homepage

sass:
  sass_dir: _sass

permalink: /posts/:title/

texture:
  title: alexander lerch
  tagline: audio content analysis
  date_format: "%b %-d, %Y"
  style: blue
  showNav: true
  showPicker: false
  navigation:
    - title: home
      url: "/"  
    - title: publications
      url: "/publications"  
    - title: photos
      url: "/photos"  
    - title: about
      url: "/about"  

  social_links:
    github:  alexanderlerch
    linkedIn: in/lerch
    rss: rss
    

domain: "alexanderlerch.github.io"
baseurl: ""

author:
  name: alexander lerch
  url: http://www.alexanderlerch.com/

plugins:
  - jekyll-seo-tag


